version: '3'

services:

  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/code
    expose:
      - "8000"
    links:
      - redis

  db:
    image: postgres:alpine

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'